apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ghost.fullname" . }}
data:
  config.production.json: |
    {
      "url": "{{ .Values.appUrl }}",
      "server": {
        "port": 2368,
        "host": "0.0.0.0"
      },
      "database": {
        "client": "mysql",
        "connection": {
          "host": "{{ .Values.dbHost }}",
          "port": 3306,
          "password": "{{ .Values.appPassword }}",
          "user": "{{ .Values.appUsername }}",
          "database": "{{ .Values.dbName }}"
        }
      },
      "mail": {
        "transport": "Direct"
      },
      "logging": {
        "transports": [
          "file",
          "stdout"
        ]
      },
      "process": "systemd",
      "paths": {
        "contentPath": "/var/lib/ghost/content"
      }
    }